### ISSUE TITLE
node encrypts wallet and exposes specified password in plain text in /var/log/syslog

### ISSUE THREAD

**Issue by mntyfrsh** [Encrypt-S/navcoin-angular#67]
Encrypting the wallet through the Navdroid UI exposes the password used to encrypt the wallet in plain text in the log. In this case, angular is configured to run via systemd and outputs to /var/log/syslog.

Example:

May 10 07:00:18 odroid node[948]: encryptwallet rpc method called with arguments: testtesttest

**Comment by proletesseract** [comment]
This issue is fixed with commit https://github.com/Encrypt-S/navcoin-express/commit/f0cfee3fc9e0f66f8d9717bb22f417cab68a56db in the navcoin-express repo.

Specifically removing line 268 of `routes/api.js`

https://github.com/Encrypt-S/navcoin-express/commit/f0cfee3fc9e0f66f8d9717bb22f417cab68a56db#diff-4e8b28a0f7943cb0fe11996dd13fd7dfL268

In the commit i've also removed a bunch of other unnecessary console logs and http responses where we were dumping the posted params back to the front end for debugging.

I also had a look at the navcoin-angular files and removed any unnecessary console logs leaving only genuine error logs.

https://github.com/Encrypt-S/navcoin-angular/commit/7a62757c61cc58004f881ea4cf3bae662cb72caa

I've tested that both projects still run but i haven't done any regression testing.
